### ISSUE TITLE
For those who want to compile with a recent opencv version (4.5.4)

### ISSUE THREAD

**Issue by Tetsujinfr** [tum-vision/online_photometric_calibration#14]
After forcing the OpenCV version to 4.5.4 in the CmakeLists.txt, since this is the version I use right now, I had this error at compilation time:
```
online_photometric_calibration/src/ImageReader.cpp: In member function ‘cv::Mat ImageReader::readImage(int)’:
/online_photometric_calibration/src/ImageReader.cpp:24:57: error: ‘CV_LOAD_IMAGE_GRAYSCALE’ was not declared in this scope
   24 |     cv::Mat image = cv::imread(m_files.at(image_index), CV_LOAD_IMAGE_GRAYSCALE);
```

Based on [this](https://github.com/BVLC/caffe/issues/6680#issuecomment-622989343), in StandardIncludes.h I added 
`#include "opencv2/imgcodecs/imgcodecs.hpp"`

And in ImageReader.cpp, in the ImageReader class readImage method I replaced `cv::Mat image = cv::imread(m_files.at(image_index), CV_LOAD_IMAGE_GRAYSCALE);` with `cv::Mat image = cv::imread(m_files.at(image_index), cv::IMREAD_GRAYSCALE);`

Compilation successful in 2021 with OpenCV 4.5.4, done!
Hope this helps someone. bye.
